apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ./repositories/framework-repository.yaml
  - ./repositories/subscriptions-repository.yaml
  - ./repositories/apis-repository.yaml
  - ./prod-gateway-tmp.yaml
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: graphman-encryption-secret
    env: ./graphman-encryption-secret.env

      
  
