apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: attendee-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: attendee-role
subjects:
- kind: ServiceAccount
  name: attendee-sa
