apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ./dev-gateway-tmp.yaml
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: dev-gateway-bundle
    files:
    -  ./dev-gateway-bundle.json