global:
  redis:
    password: "73wREf2YhxoUZ6j7auNz"

image:
  registry: docker.io
  repository: bitnami/redis
  tag: 7.2.1-debian-11-r0
  pullPolicy: IfNotPresent

architecture: replication

auth:
  enabled: false
  sentinel: true
  password: "73wREf2YhxoUZ6j7auNz"

master:
  count: 1
  configuration: ""
  disableCommands:
    - FLUSHDB
    - FLUSHALL
  # containerPorts:
  #   redis: 6379
  persistence:
    enabled: true
    size: 100Gi
  service:
    type: LoadBalancer
    # ports:
    #   redis: 6379
  serviceAccount:
    create: false
    name: ""
    automountServiceAccountToken: true
    annotations: {}

replica:
  replicaCount: 3
  containerPorts:
    redis: 6379

  resources:
    limits: {}
    requests: {}

  persistence:
    enabled: true
    sizeLimit: ""
    accessModes:
      - ReadWriteOnce
    size: 100Gi
  service:
    type: LoadBalancer
    externalTrafficPolicy: Cluster
    # ports:
    #   redis: 6379
  serviceAccount:
    create: false
    name: ""
    automountServiceAccountToken: true
    annotations: {}

sentinel:
  enabled: true
  service:
    type: LoadBalancer
    externalTrafficPolicy: Local
  image:
    registry: docker.io
    repository: bitnami/redis-sentinel
    tag: 7.2.1-debian-11-r0
    digest: ""
    pullPolicy: IfNotPresent
  masterSet: mymaster
  quorum: 2
  # containerPorts:
  #   sentinel: 26379
  resources:
    limits: {}
    requests: {}

pdb:
  create: true
  minAvailable: 1
  maxUnavailable: ""

tls:
  ## @param tls.enabled Enable TLS traffic
  ##
  enabled: true
  ## @param tls.authClients Require clients to authenticate
  ##
  authClients: false
  ## @param tls.autoGenerated Enable autogenerated certificates
  ##
  autoGenerated: true
  ## @param tls.existingSecret The name of the existing secret that contains the TLS certificates
  ##
  existingSecret: ""
  ## @param tls.certificatesSecret DEPRECATED. Use existingSecret instead.
  ##
  certificatesSecret: ""
  ## @param tls.certFilename Certificate filename
  ##
  certFilename: ""
  ## @param tls.certKeyFilename Certificate Key filename
  ##
  certKeyFilename: ""
  ## @param tls.certCAFilename CA Certificate filename
  ##
  certCAFilename: ""
  ## @param tls.dhParamsFilename File containing DH params (in order to support DH based ciphers)
  ##
  dhParamsFilename: ""